#include<iostream>
using namespace std;
main()
{
	float num1;
	float num2;
	float num3;
	float num4;
	float num5;
	float num6;
	float num7;
	float num8;
	float num9;
	float num10;
	float num11;
	float num12;
	float num13;
	float num14;
	float num15;
	float r1;
	float r2;
	float r3;
	float result;
	cout<<"Number 1: ";
	cin>>num1;
	cout<<"Number 2: ";
	cin>>num2;
	cout<<"Number 3: ";
	cin>>num3;
	cout<<"Number 4: ";
	cin>>num4;
	cout<<"Number 5: ";
	cin>>num5;
	cout<<"Number 6: ";
	cin>>num6;
	cout<<"Number 7: ";
	cin>>num7;
	cout<<"Number 8: ";
	cin>>num8;
	cout<<"Number 9: ";
	cin>>num9;
	cout<<"Number 10: ";
	cin>>num10;
	cout<<"Number 11: ";
	cin>>num11;
	cout<<"Number 12: ";
	cin>>num12;
	cout<<"Number 13: ";
	cin>>num13;
	cout<<"Number 14: ";
	cin>>num14;
	cout<<"Number 15: ";
	cin>>num15;
	r1=num1+num2+num3+num4+num5;
	r2=num6*num7*num8*num9*num10;
	r3=num11-num12-num13-num14-num15;
	result=r1+r2-r3;
	cout<<"The final result is: "<<result;
}
